### ISSUE TITLE
Docker Documentation

### ISSUE THREAD

**Issue by 1h8fulkat** [omriasta/ifitsync#2]
This is a fantastic project!

For anybody interested, this is implemented in Docker by cloning this Repo, obtaining the token.pickle file and copying it into the directory then using the following Dockerfile:

```
FROM python:3.8-slim-buster

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install dependencies:
COPY requirements.txt .
RUN pip install -r requirements.txt

# Run the application:
RUN mkdir /ifitsync
WORKDIR /ifitsync

CMD ["python", "ifitsync.py"]
```

After building the image, run it with the following command:

`docker run  -d  --name ifitsnyc  -v ~/ifitsync:/ifitsync <image name>`

**Comment by omriasta** [comment]
Thanks, I'll copy this into the wiki area. Glad you got it working :)

**Comment by omriasta** [comment]
Added to Wiki:
https://github.com/omriasta/ifitsync/wiki/Docker-Instructions
