### ISSUE TITLE
Token expiration

### ISSUE THREAD

**Issue by 1h8fulkat** [omriasta/ifitsync#3]
I'm getting the following error after a few days when I run the cron job every 6 hours.  When I refresh the pickle file via GUI, it works again for a few days.  It seems the script is not updating the token after it runs.

Traceback (most recent call last):

  File "ifitsync.py", line 25, in <module>

    service = main()

  File "/ifitsync/get_googleaccount.py", line 39, in main

    creds.refresh(Request())

  File "/opt/venv/lib/python3.8/site-packages/google/oauth2/credentials.py", line 200, in refresh

    access_token, refresh_token, expiry, grant_response = _client.refresh_grant(

  File "/opt/venv/lib/python3.8/site-packages/google/oauth2/_client.py", line 248, in refresh_grant

    response_data = _token_endpoint_request(request, token_uri, body)

  File "/opt/venv/lib/python3.8/site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request

    _handle_error_response(response_body)

  File "/opt/venv/lib/python3.8/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response

    raise exceptions.RefreshError(error_details, response_body)

google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}')

Traceback (most recent call last):

  File "ifitsync.py", line 25, in <module>

    service = main()

  File "/ifitsync/get_googleaccount.py", line 39, in main

    creds.refresh(Request())

  File "/opt/venv/lib/python3.8/site-packages/google/oauth2/credentials.py", line 200, in refresh

    access_token, refresh_token, expiry, grant_response = _client.refresh_grant(

  File "/opt/venv/lib/python3.8/site-packages/google/oauth2/_client.py", line 248, in refresh_grant

    response_data = _token_endpoint_request(request, token_uri, body)

  File "/opt/venv/lib/python3.8/site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request

    _handle_error_response(response_body)

  File "/opt/venv/lib/python3.8/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response

    raise exceptions.RefreshError(error_details, response_body)

google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}'

**Comment by omriasta** [comment]
Hmmm...this looks like an issue with your google account. I'll take a better look tomorrow but I run mine only once a day and it hasn't expired in months...
I'm using the python library directly from Google and the error you are getting isn't in the script but rather coming from the google python file that refreshes the token.

**Comment by omriasta** [comment]
Actually quick thought, any chance that the project you created in the google console is shared with something else? I'm wondering if something else is using the refresh token and rendering the stored token invalid?

**Comment by 1h8fulkat** [comment]
I do have multiple projects, but this one is specific to this one instance - it's not used anywhere else.  I was refreshing 1x per day originally and increased the frequency thinking that I may have been expiring at some point during the day - that was obviously not the problem.  I did use the [link ](https://console.cloud.google.com/flows/enableapi?apiid=fitness) in your forked fitsync repo to setup the API access.  I assume it just needed an OAuth service account and consent screen.

**Comment by omriasta** [comment]
No the refresh token should be good as long as it's used within 6 months from what I read. If you aren't revoking access to the program, maybe there is some issue with permissions to the token.pickle file? I saw that you have it in docker so not sure if that may be causing it (I'm not running in docker myself). The get google account script is pretty much copy pasted from the "python quick start example" here https://developers.google.com/docs/api/quickstart/python
Given the script is the same maybe try running that as the error is coming from that script and that is provided by google.

**Comment by omriasta** [comment]
Also, you mentioned several projects, apparently google has a limit on how many token refreshes you get...it appears that also throws the same error...others have also suggested just nuking the project and starting over with new credentials.json file....

**Comment by omriasta** [comment]
Looking over your docker instructions, and forgive me it's not my strongest knowledge, how exactly does that work? You build the image using the docker file that you provided, then create a container with the image. When you start the container, doesn't the script run once and the container stops? You mentioned you were using the cron script but not sure how exactly if you are running in docker? Wouldn't it make more sense to just restart the container using cron rather than my cron script?

**Comment by 1h8fulkat** [comment]
I'll try to rebuild the project on the google side to see if that helps, I'll also check the permissions.  The token.pickle file is being modified as the last run time, so it certainly seems like the problem is on the Google side somewhere.

Regarding the Docker configuration.  Essentially the Dockerfile builds a python image with a virtual environment that has all the requirements in your requirements.txt file.  It then sets it to execute the command _python ifitsync.py_ when it is launched.  When I create the container, using that image, I mount the cloned repo path to the correct container path using _-v ~/ifitsync:/ifitsync_ so that the container has access to read/write all of the files on the one path as well as the ability to actually access ifitsync.py.  I have a cronjob on the host that launches the container on a recurring basis with the command _docker start ifitsync_

**Comment by omriasta** [comment]
Are you sure that the virtual environment is being activated so that the script runs inside the virtual environment? I am not familiar with your base image so I could be wrong but I don't see anything that ensures the script runs inside the venv. One other thought might be the time settings inside the docker container.

**Comment by omriasta** [comment]
Ok, just ran a quick test with docker and was able to get it working but you can drop the 3 lines that create a virtual env, there is no need for this if you are containerized and all set with python 3.8. The virtual environment is more for someone that has multiple python versions and to make sure that they are in the right version where you already have the requirements installed.
I'll also update the wiki as you need to first run this outside of docker to get ifit-credentials.json, token.pickle and also make sure that the const.py is already set.

**Comment by 1h8fulkat** [comment]
Great!  I'll give it a shot without the venv too.  I'll verify my const.py is set as well.

**Comment by omriasta** [comment]
I only ran it once and you said it was working for a bit before it stopped so not sure that this is the culprit...you may want to change the container to just run python, that way it shouldn't stop and then you can actually execute a shell in the container and troubleshoot further (ie look into the timezone settings etc).

**Comment by 1h8fulkat** [comment]
I noticed it takes a week to expire the token.  I've rebuilt the project on Google and removed the venv from the image.  I'll give it a week and see if that was the culprit, if it expires again, I'll attempt to run it sans Docker for a week and see if I can reproduce.  If I can't I know it has something to do with the container at the very least.  Thanks for the help with this!

**Comment by 1h8fulkat** [comment]
The token expired again yesterday.  I'm going to try to remove it from the Docker Container and run it for a week in just the VENV and see if there is any difference.

**Comment by 1h8fulkat** [comment]
It looks like I am getting an error now on the venv after it uploads 3 workouts:

`Traceback (most recent call last):
  File "ifitsync.py", line 692, in <module>
    UploadIfitSessionToGoogle(y)
  File "ifitsync.py", line 557, in UploadIfitSessionToGoogle
    raise error
  File "ifitsync.py", line 555, in UploadIfitSessionToGoogle
    service.users().sessions().update(userId="me", sessionId=IfitWorkoutJson.id, body=session_body,).execute()
  File "/home/<user>/ifitsync/venv/lib/python3.5/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/<user>/ifitsync/venv/lib/python3.5/site-packages/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://fitness.googleapis.com/fitness/v1/users/me/sessions/60115d88656cdf2a28e8edc6?alt=json returned "No permission to modify data for this source.">
`

**Comment by omriasta** [comment]
Looks like this is one of 2 issues. It's either that you don't have permissions for this scope. To fix that you would have to reauthorize the app so that all the scopes are approved. The second more likely is that your token is expired or the access to the project was revoked.

**Comment by omriasta** [comment]
Curious, what do you have set as "activityType" on line 551 of ifitsync.py?

**Comment by 1h8fulkat** [comment]
> Curious, what do you have set as "activityType" on line 551 of ifitsync.py?

 activityType=8,

I noticed this morning when I attempted a sync I got the same error described [here ](https://github.com/omriasta/ifitsync/issues/3#issuecomment-774285469) however the error occurred at the 4th tracked activity, not the 3rd.  On a hunch I modified line 94 in get_ifitaccount.py to 

` "&perPage=3"` 

instead of 5 and I synced without issue.  I noticed that it occurs during the session sync phase of that run.  So it appears something is corrupted for that run on the ifit side.

I am going to try to run for a week now using your scheduled task with the current config (outside of Docker) to see if the token refresh issue still occurs.

**Comment by omriasta** [comment]
odd, I have never seen this with any run. I'm curious what could be off in the data.....it's even more interesting since it doesn't fail to get the data...just to upload it to google. I guess there is an odd chance that this particular workout id exists in google already and therefore you can't overwrite it? Let's hope it goes well moving forward...

**Comment by 1h8fulkat** [comment]
I got the same error today, 1 week after I last generated the token.pickle file, running it in venv (not Docker) so it definitely looks like it's on the Google side.  Regenerating the token.pickle file on a GUI enabled system fixes it for another week:

`Traceback (most recent call last):
  File "./ifitsync.py", line 24, in <module>
    service = main()
  File "/home/<user>/ifitsync/get_googleaccount.py", line 39, in main
    creds.refresh(Request())
  File "/home/<user>/ifitsync/venv/lib/python3.5/site-packages/google/oauth2/credentials.py", line 206, in refresh
    self._scopes,
  File "/home/<user>/ifitsync/venv/lib/python3.5/site-packages/google/oauth2/_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/<user>/ifitsync/venv/lib/python3.5/site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/home/<user>/ifitsync/venv/lib/python3.5/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}')
`
I was hoping you could review how I created the project.

I created the project using [this ](https://console.cloud.google.com/flows/enableapi?apiid=fitness) link.  After creation, I setup the OAuth consent screen and enabled the 48 possible scopes, then I added my email as a test user.  I then created the OAuth 2.0 Client ID and downloaded the JSON file to be used with your repo. 

It seemed pretty straightforward.  Am I missing anything?  Did you setup your project any differently?

**Comment by omriasta** [comment]
I'm not sure what the link you are using does, it appears to create something different from what I have.
I would just start from scratch by creating a blank project, then manually enabling the api as I wrote in the instructions. My "Oauth consent screen" tab shows that it is in production and I did not add any of the scopes in there, that is later requested by the script itself. Once you have a blank project in the library, tab find and enable the Fit api, finally credentials tab, create credentials, oauth client id, select web application and give it a name, leave the others as they are and then you can download the json file.
Let me know how that goes.

**Comment by 1h8fulkat** [comment]
My consent screen was in "testing" not production, and I had configured myself as a "test user".  I'm not sure if that would make a difference.  I've created a new project, used a "limited input device" OAuth 2.0 Client ID.  I recreated the consent screen with no scopes and attempted the sync again.  Everything seems to be working, I guess I'll know in 7 days.  Thanks for the guidance!

**Comment by omriasta** [comment]
Not sure if limited input is the best choice but shouldn't make much of a
difference. Sorry, I'm not 100% familiar with the google oauth library, I
also just followed their own instructions. Hopefully this will work out
better...

**Comment by omriasta** [comment]
Also, I assume you replaced the credentials.json file and also wiped the token.pickle file?

**Comment by 1h8fulkat** [comment]
It's one of the few that works since most of the JSON credential files don't start with "installed" which is what it looks like your script is looking for.  Which type of account did you create?

Yes I wiped and replaced the credentials file and the token.pickle file

**Comment by omriasta** [comment]
Pretty sure I used web application but I could be wrong...don't remember anymore...the part that uses this file was all directly from the google example.
Actually just double checked and mine is "Desktop application" but it looks like these 2 types are identical.

**Comment by omriasta** [comment]
And this is what my consent screen looks like:
![Screenshot from 2021-02-15 10-55-44](https://user-images.githubusercontent.com/11823048/107968503-6ff6b880-6f7c-11eb-90db-f02313862e35.png)

**Comment by 1h8fulkat** [comment]
From what I could see, only the JSON ID's that have "Installed" at the beginning would work.  Originally I was trying with Web Application and I was having problems.  My consent screen looks like yours (now), I'm hopeful that it will work now that I've corrected the scope issue and published the consent screen.

**Comment by omriasta** [comment]
Any update on this?

**Comment by 1h8fulkat** [comment]
Good news! Today was day 8 and it synced properly.  Normally I would get a token expiration after 7 days.  It looks like it was definitely related to one of the things described above on the project configuration.  Thank you for your help!

**Comment by omriasta** [comment]
No worries, glad it worked out!
