### ISSUE TITLE
iFit Data Question

### ISSUE THREAD

**Issue by KenGrinder** [omriasta/ifitsync#6]
Is a premium membership required through iFit to transfer all access/sync all of the data?

I haven't used the iFit app that much so I'm not extremely familiar with it.

I appreciate the project, thanks!

**Comment by omriasta** [comment]
I am not sure, I have a membership so that is all I can test. I assume if you have the app installed and can view your past workouts in the app or website, you should be good.

**Comment by KenGrinder** [comment]
I actually did login to the website and it does appear to still have a majority of all the data, thanks!

**Comment by omriasta** [comment]
Yep, the script hooks up to the API that the site and app use in the background so it should be able to pull the data. Let me know if you run into any issues.

**Comment by omriasta** [comment]
Any luck?

**Comment by KenGrinder** [comment]
Yes. The script does work excellently!

I have shifted to using the qdomyos-zwift recently so I can use my iFit bike with Zwift, and didn't realize it also supports exports riding data to Strava (Which syncs with Fitbit).

I appreciate all your help and work on the project though!
