### ISSUE TITLE
cannot login to iFit

### ISSUE THREAD

**Issue by harphere** [omriasta/ifitsync#7]
Hi, came across your project, it looks great but I'm having trouble logging into iFit when running `python ifitsync.py`.
I enter my iFit email and password and it returns:
```
Traceback (most recent call last):
  File "ifitsync.py", line 2, in <module>
    from get_ifitaccount import HISTORY_JSON, IFIT_HIST_HEADERS
  File "/home/pi/ifitsync/get_ifitaccount.py", line 98, in <module>
    clientid_list = re.findall(regex_clientid, scripts[0].text_content())
IndexError: list index out of range
```
I created my iFit account using Google credentials.

**Comment by omriasta** [comment]
Haven't looked at this in a while since they added the sync directly to the app. It looks like they may have changed the website, I'll take a look as soon as I have a chance tomorrow.

**Comment by omriasta** [comment]
It looks the same to me. Can you go to https://www.ifit.com/settings/apps
And right click-> view source 
Then search for "clientid" ? There should be a few entries joined by a "clientsecret". The script is basically trying to scrape these values. It's possible that since you are signing in with Google credentials that the scrape is failing. After that, all the interactions are with the API directly, just not sure how that will react with Google credentials as well...

**Comment by harphere** [comment]
Thanks for getting back quickly. I overlooked adding an app in my profile. Got it working now, thanks again.

**Comment by omriasta** [comment]
Glad it worked out!

**Comment by srsholmes** [comment]
> It looks the same to me. Can you go to https://www.ifit.com/settings/apps And right click-> view source Then search for "clientid" ? There should be a few entries joined by a "clientsecret". The script is basically trying to scrape these values. It's possible that since you are signing in with Google credentials that the scrape is failing. After that, all the interactions are with the API directly, just not sure how that will react with Google credentials as well...

Hey I don't suppose you have had issues with the ifit API being unauthorized using this method of authentication? 

I am getting the following response when trying to authenticate 

```
{ code: 'UnauthorizedError', message: 'Unauthorized' }
```

I feel like they have changed their API recently, and the clientID / Secret no longer is working for me. 

For reference, this is my authentication post, written as a fetch in TS. 

```typescript
const res: iFitAuthResponse = await fetch(
    'https://api.ifit.com/oauth/token',
    {
      method: 'POST',
      body: JSON.stringify({
        grant_type: 'refresh_token',
        refresh_token: credentials['refresh_token'],
        client_id: process.env.IFIT_CLIENT_ID,
        client_secret: process.env.IFIT_CLIENT_SECRET,
      }),
      headers: {
        Host: 'api.ifit.com',
        Connection: 'keep-alive',
        Origin: 'https://onboarding-webview.ifit.com',
        'User-Agent':
          'Mozilla/5.0 (Linux; Android 6.0; Google Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.186 Safari/537.36',
        'content-type': 'application/json',
        Accept: '*/*',
        Referer:
          'https://onboarding-webview.ifit.com/0.27.0/index.html?page=login-email',
        'Accept-Encoding': 'gzip, deflate',
        'Accept-Language': 'en-US,en;q=0.9',
        'X-Requested-With': 'com.ifit.wolf',
      },
    }
  ).then((x) => x.json());
```

Do you happen to know if there are any additional / changed headers needed to auth now?

**Comment by omriasta** [comment]
I haven't had any issues getting refresh tokens but I haven't tried to "re-authenticate" in a very long time. My script has been working for me without issues.

**Comment by srsholmes** [comment]
Thanks for letting me know, I'll investigate further a d post a solution if I find one 👍
